### ISSUE TITLE
UnicodeEncodeError - Todos do not extract

### ISSUE THREAD

**Issue by raik** [robcowie/SublimeTODO#32]
The folder where the file is based is named Kübertöökoda. Maybe it helps.

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
  File "./todo.py", line 289, in run
  File "./todo.py", line 226, in format
  File "./todo.py", line 172, in extract
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0308' in position 26: ordinal not in range(128)
```

**Comment by robcowie** [comment]
Upgrade (if you use Package Control it should already be done). Let me know if the problem is fixed.

**Comment by raik** [comment]
Fixed. Thanks.
