### ISSUE TITLE
Failure if symlink points to non-existing file

### ISSUE THREAD

**Issue by robcowie** [robcowie/SublimeTODO#4]
Hi Rob,

when I scan my project for to do items, I get the following in the console (sanitizing file names):

```
scan: xxx has been seen before, skipping
# [.. similar lines omitted ..]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./todo.py", line 222, in run
  File "./todo.py", line 176, in format
  File "./todo.py", line 143, in extract
IOError: [Errno 2] No such file or directory: u'zzz'
```

Here, zzz is the absolute name of a symlink that points to a nonexisting file.

Version is: "2011.12.19.20.10.31" (from package-metadata.json).

Thanks,
Kai

**Comment by kgrossjo** [comment]
Thank you, sir, it works nicely.
