### ISSUE TITLE
Sublime Text 3 support

### ISSUE THREAD

**Issue by staticdreams** [robcowie/SublimeTODO#47]
This is a very useful package. I cant leave without in ST2. 
But ST3 breaks support. Please update it to support Python 3 (or whatever is causing this  incompatibility)

```
Exception in thread Thread-289:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "/Users/Peter/Library/Application Support/Sublime Text 3/Installed Packages/SublimeTODO.sublime-package/todo.py", line 292, in run
    rendered = list(self.renderer.format(todos))
  File "/Users/Peter/Library/Application Support/Sublime Text 3/Installed Packages/SublimeTODO.sublime-package/todo.py", line 229, in format
    messages = sorted(messages, key=key_func)
  File "/Users/Peter/Library/Application Support/Sublime Text 3/Installed Packages/SublimeTODO.sublime-package/todo.py", line 178, in extract
    matches = [Message(msg_type, msg) for msg_type, msg in mo.groupdict().iteritems() if msg]
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by FeliciousX** [comment]
Totally agree with you! I'd hate to see this go away in ST3

**Comment by pokidovea** [comment]
I join

**Comment by chrisspiegl** [comment]
Hop to get this soon. It is a very valuable plugin.

**Comment by wolffc** [comment]
Please update the package for sublime 3 Support.

**Comment by johnathanz** [comment]
duplicate of https://github.com/robcowie/SublimeTODO/issues/62.

Suggest close issue...
