### ISSUE TITLE
'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by yahyaerturan** [robcowie/SublimeTODO#60]
Using SublimeText3. Gives errors when it runs:

``` python
Scanning D:\web_projects\vOtopazari\framework\application\controllers\home.php
Exception in thread Thread-16:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "todo in D:\developer_apps\SublimeText-3\Data\Installed Packages\SublimeTODO.sublime-package", line 292, in run
  File "todo in D:\developer_apps\SublimeText-3\Data\Installed Packages\SublimeTODO.sublime-package", line 229, in format
  File "todo in D:\developer_apps\SublimeText-3\Data\Installed Packages\SublimeTODO.sublime-package", line 178, in extract
AttributeError: 'dict' object has no attribute 'iteritems'
```

My applied settings are:

``` javascript
"todo":
  {
      "file_exclude_patterns":[
        "*.css", "*.po", "*.mo"
      ],
      "folder_exclude_patterns": [
        "static", "vendor", "tmp"
      ],
      "patterns":
      {
        "TODO": "TODO[(]*.*[)]*:+(?P<todo>.*)$",
      "NOTE": "NOTE[(]*.*[)]*:+(?P<note>.*)$",
      "FIXME": "FIX ?ME[(]*.*[)]*:+(?P<fixme>\\S.*)$",
      "CHANGED": "CHANGED[(]*.*[)]*:+(?P<changed>\\S.*)$",
      "BUG": "BUG[(]*.*[)]*:+(?P<bug>.*)$",
      "FILE": "@file+(?P<file>.*)$"
      },
      "case_sensitive": true,
      "result_title": "TODO Results"
  }
```

And keys:

``` javascript
[
  { "keys": ["ctrl+shift+t"], "command": "todo", "args": {"open_files_only": false} },
]
```

**Comment by arturbekasov** [comment]
Same thing. ST3, Ubuntu 12.04 64 bit. Default configuration.

**Comment by thefirstofthe300** [comment]
Have you cloned the st3 branch of the repo.  You might want to look at the issue about ST3 compatibility.

**Comment by lizzzzard** [comment]
+1 here.
ST3, Windows 7 64 bit, default configuration.
I did not install the st3 branch, will try that next.

**Comment by svenfraeys** [comment]
Also with me, ST3. code need to be python 3 compatible
